# from https://github.com/vincentml/xml-catalog-resolver

name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEX_VERSION: ${{ matrix.basex }}
    strategy:
      matrix:
        java: ["8", "17"]
        basex: ["9.7", "9.7.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          architecture: x64
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test